/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dd_pll.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9e5eb34d85fd883d802fa854f13d417a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dd_pllv2/dd_pll.h>
// pydoc.h is automatically generated in the build directory
#include <dd_pll_pydoc.h>

void bind_dd_pll(py::module& m)
{

    using dd_pll = gr::dd_pllv2::dd_pll;


    py::class_<dd_pll, gr::block, gr::basic_block, std::shared_ptr<dd_pll>>(
        m, "dd_pll", D(dd_pll))

        .def(py::init(&dd_pll::make),
             py::arg("bw") = 0.0628,
             py::arg("damp") = 1.0,
             py::arg("constellation"),
             py::arg("min_freq") = -1.0,
             py::arg("max_freq") = 1.0,
             D(dd_pll, make))


        ;
}
